<?php
	$js_files = array(
		'libs/jquery.js',
		'libs/jquery.form.js',
		'libs/jquery.blockUI.js',
		'libs/jquery.livequery.js',
		'libs/jquery.metadata.js',
		'libs/highcharts.js',
		'libs/jquery.lazyload.mini.js',
		'libs/jquery.uploader.js',
		'libs/AC_RunActiveContent.js',
		'libs/jquery.flash.js',
		'libs/jquery.autocomplete.js',
		'libs/jquery.fuploader.js',
		'libs/swfobject.js',
		'libs/jquery.phototag.js',
		'libs/jquery-ui-1.7.3.custom.min.js',
		'libs/date.format.js',
		'libs/jquery.truncate-2.3.js',
		'libs/jquery.colorbox.js',
		'libs/jquery.overlabel.js',
		'libs/jquery.easing.1.3.js',
		'libs/jquery.coda-slider.js',
		'libs/jquery.cookie.js',
		'libs/jquery.timepickr.js',
		'libs/jquery.timeago.js',
		'common.js'
	);
?>